/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

type Def$db5c56a6 = {
  /**
   * Map
   * 
   * The map of dynamic zones to slots.
   */
  'map': Array<{
    /**
     * Croct slot
     * 
     * The ID of the slot as defined in Croct.
     */
    'slot': string,
    /**
     * Strapi component
     * 
     * The ID of the component as defined in Strapi.
     */
    'component': string,
  }>,
};

declare module '@croct/plug/slot' {
  type LaunchpadHomeDynamicZonesV1 = Def$db5c56a6 & {'_component': 'strapi-dynamic-zone-map@1' | null};
  
  export interface VersionedSlotMap {
    'launchpad-home-dynamic-zones': {
      latest: LaunchpadHomeDynamicZonesV1,
      '1': LaunchpadHomeDynamicZonesV1,
    };
  }
}

export {};